# Generated by Django 2.2.26 on 2022-10-07 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0068_auto_20221006_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='date_begin',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date begin'),
        ),
        migrations.AlterField(
            model_name='project',
            name='date_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date end'),
        ),
    ]
