# Generated by Django 2.2.26 on 2022-10-10 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0069_auto_20221007_0738'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='date_begin',
        ),
        migrations.RemoveField(
            model_name='project',
            name='date_end',
        ),
    ]
