# Generated by Django 2.2.26 on 2022-11-04 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0071_expired'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Expired',
        ),
    ]
