# Generated by Django 2.2.26 on 2022-10-10 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userstories', '0021_auto_20201202_0850'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstory',
            name='date_begin',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date begin'),
        ),
        migrations.AddField(
            model_name='userstory',
            name='date_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date end'),
        ),
    ]
