# Generated by Django 2.2.26 on 2022-10-18 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userstories', '0023_auto_20221017_0752'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userstory',
            old_name='date_begin',
            new_name='begin_task_date',
        ),
        migrations.RenameField(
            model_name='userstory',
            old_name='date_end',
            new_name='end_task_date',
        ),
    ]
