# Generated by Django 2.2.26 on 2022-10-18 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userstories', '0024_auto_20221018_0735'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userstory',
            old_name='end_task_date',
            new_name='end_date_task',
        ),
        migrations.RenameField(
            model_name='userstory',
            old_name='begin_task_date',
            new_name='start_date_task',
        ),
    ]
