# Generated by Django 2.2.26 on 2022-10-18 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userstories', '0025_auto_20221018_0740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstory',
            name='end_date_task',
            field=models.DateField(blank=True, null=True, verbose_name='end date task'),
        ),
        migrations.AlterField(
            model_name='userstory',
            name='start_date_task',
            field=models.DateField(blank=True, null=True, verbose_name='start date task'),
        ),
    ]
