# Generated by Django 2.2.26 on 2022-11-04 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userstories', '0026_auto_20221018_0944'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expired',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_expired', models.BooleanField(verbose_name='is expired')),
            ],
        ),
    ]
