# Generated by Django 2.2.26 on 2022-11-04 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userstories', '0027_expired'),
    ]

    operations = [
        migrations.AddField(
            model_name='expired',
            name='user_story',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userstories.UserStory'),
        ),
    ]
