# Generated by Django 2.2.26 on 2022-11-23 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userstories', '0032_auto_20221123_0810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstory',
            name='is_late',
            field=models.BooleanField(default=False, verbose_name='is late'),
        ),
    ]
