# Generated by Django 2.2.26 on 2022-10-17 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0010_auto_20221014_0740'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='date_begin',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='date_end',
        ),
    ]
